# Generated by Django 6.0 on 2025-12-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.RenameModel(
            old_name='CarModels',
            new_name='CarModel',
        ),
    ]
