# Generated by Django 6.0 on 2026-01-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_brands_brand_rename_cars_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=255)),
                ('horsepower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhaust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TyreSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WheelDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inch', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModelBrake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interior_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interior_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exterior_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exterior_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exterior_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('car_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.engine')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelExhaust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('exhaust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.exhaust')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.featurecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_transmissions', to='cars.carmodel')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='WheelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.tyre')),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.tyresize')),
                ('wheel_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.wheeldesign')),
                ('wheel_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.wheelsize')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_features', to='cars.carmodel')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.feature')),
            ],
            options={
                'unique_together': {('car_model', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='CarModelWheelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_packages', to='cars.carmodel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.wheelpackage')),
            ],
            options={
                'unique_together': {('car_model', 'package')},
            },
        ),
    ]
