# Generated by Django 6.0 on 2026-01-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brake_color_engine_exhaust_featurecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brake',
            options={'verbose_name': 'Brake', 'verbose_name_plural': 'Brakes'},
        ),
        migrations.AlterModelOptions(
            name='carmodelbrake',
            options={'verbose_name': 'Car Model Brake', 'verbose_name_plural': 'Car Model Brakes'},
        ),
        migrations.AlterModelOptions(
            name='featurecategory',
            options={'verbose_name': 'Feature Category', 'verbose_name_plural': 'Feature Categories'},
        ),
        migrations.AlterField(
            model_name='carmodelbrake',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_brakes', to='cars.carmodel'),
        ),
        migrations.AlterField(
            model_name='carmodelengine',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_engine_set', to='cars.carmodel'),
        ),
    ]
