# Generated by Django 6.0 on 2026-04-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_brake_options_alter_carmodelbrake_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodelexhaust',
            options={'verbose_name': 'Car Model Exhaust', 'verbose_name_plural': 'Car Model Exhausts'},
        ),
        migrations.AlterModelOptions(
            name='exhaust',
            options={'verbose_name': 'Exhaust', 'verbose_name_plural': 'Exhausts'},
        ),
        migrations.AlterField(
            model_name='carmodelexhaust',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_exhausts', to='cars.carmodel'),
        ),
    ]
