# Generated by Django 6.0 on 2026-06-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cart_cartitem_cartitemconfiguration_cartitemfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_price',
            new_name='unit_price',
        ),
    ]
