# Generated by Django 6.0 on 2026-06-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_total_price_cartitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Feature Category', 'verbose_name_plural': 'Feature Categories'},
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='is_configurable',
            field=models.BooleanField(default=False, help_text='Can customers choose an option from this category?'),
        ),
    ]
