# Generated by Django 6.0 on 2026-07-28 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_featurecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelengine',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_engine', to='cars.carmodel'),
        ),
        migrations.CreateModel(
            name='CarModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.carmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
