# Generated by Django 6.0 on 2026-08-07 03:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carmodelengine_car_model_carmodelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('plug_in_hybrid', 'Plug-in Hybrid'), ('electric', 'Electric')], default='petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_cars', to='cars.carmodel'),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedcar',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='exterior_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='used_cars', to='cars.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedcar',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('plug_in_hybrid', 'Plug-in Hybrid'), ('electric', 'Electric')], default='Petrol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedcar',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='transmission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='used_cars', to='cars.transmission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedcar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usedcar',
            name='vin',
            field=models.CharField(default='AAAAAAAAAAAAAAAAA', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 17-character VIN in uppercase.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
    ]
