# Generated by Django 6.0 on 2026-08-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_engine_fuel_type_usedcar_car_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedcar',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='usedcar',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='usedcar',
            name='model_name',
        ),
        migrations.AddField(
            model_name='usedcar',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='used_cars', to='cars.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedcar',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedcar',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
