# Generated by Django 6.0 on 2026-08-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_accessory_usedcar_code_alter_carmodel_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='cars.accessory')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'unique_together': {('accessory', 'car', 'year')},
            },
        ),
    ]
